apiVersion: v1
kind: Service
metadata:
  name: mailer-cluster-ip-service
  namespace: nvg-cdp
spec:
  type: ClusterIP
  selector:
    component: mailer
  ports:
    - port: 54089
      targetPort: 54089